parameters:
    currency: ETH
    pm_account: U10168601
    pm_currency: USD
    pm_phrase: u1Eo5GsO75SSs3CqWHOfIPwir
    adv_acc_email: simon2016burns@gmail.com
    adv_currency: USD
    adv_password: FdvgJyt1257Fdg!%
    payeer_id: 132886225
    payeer_currency: USD
    payeer_secret: 4sWZwUZPXEyTQ8J5