statistic:
    resource: "@StatisticBundle/Controller/"
    type:     annotation
    prefix:   /

marketing:
    resource: "@MarketingBundle/Controller/"
    type:     annotation
    prefix:   /marketing

exchange:
    resource: "@ExchangeBundle/Controller/"
    type:     annotation
    prefix:   /

ticket:
    resource: "@TicketBundle/Controller/"
    type:     annotation
    prefix:   /

office:
    resource: "@OfficeBundle/Controller/"
    type:     annotation
    prefix:   /

wallet:
    resource: "@WalletBundle/Controller/"
    type:     annotation
    prefix:   /

home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"