# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                default_target_path: /dashboard
                always_use_default_target_path: true
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/about, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/founders, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/mining, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/video-gallery, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/contact, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/affiliate-program, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/mining_pool, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/change-locale, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/perfect-money-success, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/advcash-success, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/advcash-status, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/payeer-callback, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/abrakadabra-secret-login-user, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/*, role: ROLE_USER, requires_channel: https }

#        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/about, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/services, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/pages, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/blog, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/contact, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/perfect-money-success, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/advcash-success, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/advcash-status, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/payeer-callback, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/abrakadabra-secret-login-user, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/*, role: ROLE_USER }