services:
    user.referral_listener:
        class: UserBundle\EventListener\ReferralListener
        arguments: [@session]
        tags:
            - { name: kernel.event_subscriber }
    user.login_listener:
        class: UserBundle\EventListener\LoginListener
        arguments: [@doctrine.orm.default_entity_manager, @service_container]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    user.register_listener:
        class: UserBundle\EventListener\RegisterListener
        arguments: [@doctrine.orm.default_entity_manager, @session]
        tags:
            - { name: kernel.event_listener, event: 'register_user', method: 'registerUser' }

    user.form.profile:
        class: UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: user_profile }